#!/bin/bash

# Playwright Test Automation Framework - Test Execution Guide
# This script demonstrates all available test commands

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PLAYWRIGHT TEST AUTOMATION FRAMEWORK - EXECUTION GUIDE        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 INSTALLATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "npm install"
echo ""

echo "✅ VERIFY INSTALLATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "npx playwright --version"
echo "npx playwright test --version"
echo ""

echo "🧪 RUN TESTS - USING NPM SCRIPTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Run all tests (headless)"
echo "npm run test:all"
echo ""
echo "# Run login tests"
echo "npm run test:login"
echo ""
echo "# Run homepage tests"
echo "npm run test:homepage"
echo ""
echo "# Run in UI mode (interactive)"
echo "npm run test:ui"
echo ""
echo "# Run with browser visible"
echo "npm run test:headed"
echo ""
echo "# Run with debugging tools"
echo "npm run test:debug"
echo ""

echo "🔧 RUN TESTS - USING PLAYWRIGHT CLI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# All tests"
echo "npx playwright test"
echo ""
echo "# Specific test file"
echo "npx playwright test tests/login.spec.js"
echo ""
echo "# Tests matching pattern"
echo "npx playwright test -g \"should login successfully\""
echo ""
echo "# Specific browser"
echo "npx playwright test --project=chromium"
echo "npx playwright test --project=firefox"
echo "npx playwright test --project=webkit"
echo "npx playwright test --project=\"Mobile Chrome\""
echo ""
echo "# With options"
echo "npx playwright test --headed"
echo "npx playwright test --debug"
echo "npx playwright test --retries=2"
echo "npx playwright test --timeout=30000"
echo ""

echo "📊 VIEW REPORTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Open HTML report"
echo "npx playwright show-report"
echo ""
echo "# Report locations:"
echo "  HTML: playwright-report/index.html"
echo "  JUnit: test-results/junit.xml"
echo "  JSON: test-results/results.json"
echo ""

echo "🎯 ADVANCED USAGE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Record test"
echo "npx playwright test --record"
echo ""
echo "# Record with headed browser"
echo "npx playwright test --headed --record"
echo ""
echo "# Update snapshots"
echo "npx playwright test --update-snapshots"
echo ""
echo "# Specific test with custom timeout"
echo "npx playwright test tests/login.spec.js --timeout=45000"
echo ""
echo "# Run tests in serial (one at a time)"
echo "npx playwright test --workers=1"
echo ""
echo "# Run multiple workers"
echo "npx playwright test --workers=4"
echo ""
echo "# List all tests"
echo "npx playwright test --list"
echo ""

echo "🌍 ENVIRONMENT VARIABLES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Disable headless mode"
echo "export HEADLESS=false"
echo ""
echo "# Enable debug mode"
echo "export DEBUG=true"
echo ""
echo "# Set slow motion (milliseconds)"
echo "export SLOW_MO=1000"
echo ""
echo "# Override base URL"
echo "export BASE_URL=https://your-app.com"
echo ""
echo "# Override credentials"
echo "export TEST_EMAIL=your@email.com"
echo "export TEST_PASSWORD=yourpassword"
echo ""
echo "# CI mode"
echo "export CI=true"
echo ""

echo "💡 COMMON WORKFLOWS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Development: Interactive testing with UI"
echo "npm run test:ui"
echo ""
echo "# Quick test run"
echo "npm run test:all"
echo ""
echo "# Debug failing test"
echo "npm run test:debug -- tests/login.spec.js"
echo ""
echo "# Run and watch (monitor file changes)"
echo "npm run test:headed -- --workers=1"
echo ""
echo "# Generate report after tests"
echo "npm run test:all && npx playwright show-report"
echo ""
echo "# Continuous testing"
echo "npx playwright test --watch"
echo ""

echo "🐛 DEBUGGING TIPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Step through test with Inspector"
echo "npx playwright test --debug"
echo ""
echo "# Slow down test execution"
echo "export SLOW_MO=2000 && npm run test:headed"
echo ""
echo "# Run single test in debug mode"
echo "npx playwright test tests/login.spec.js -g \"should login\" --debug"
echo ""
echo "# Enable trace recording"
echo "npx playwright test --trace on"
echo ""
echo "# View trace"
echo "npx playwright show-trace trace.zip"
echo ""

echo "📝 CONTINUOUS INTEGRATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Run with CI settings"
echo "export CI=true"
echo "npm run test:all"
echo ""
echo "# Alternative"
echo "CI=true npm run test:all"
echo ""

echo ""
echo "✨ Framework ready! Choose your test command above and get started."
echo ""
